### PR TITLE
feat: support @vite/plugin-legacy

### PR DESCRIPTION
**Pull request by WOSHIZHAZHA120**
#27

Some code is reference from https://github.com/jthomaschewski/laravel-vite/tree/feat-vite-legacy

### CODE REVIEW

**Comment by innocenzi** [comment]
Looks nice, is that all is required? Hoes does that one line work: `'polyfills-legacy'`? Does the legacy plugin add that to the manifest? 

Also can you apply php-cs-fixer?

**Comment by WOSHIZHAZHA120** [comment]
This is legacy polyfills entry

图片

$safariFix is  [Safari 10.1 nomodule support](https://gist.github.com/samthor/64b114e4a4f539915a95b91ffd340acc#file-safari-nomodule-js)
$bundleLoader is a checker if  browser not supported import syntax then use System.import to instead

**Comment by WOSHIZHAZHA120** [comment]
Also php-cs-fixer applied.

**Comment by innocenzi** [comment]
Thanks! I'll check this out as soon as I can and hopefully I can merge and release.

**Comment by innocenzi** [comment]
Seems like you disabled the right for me to update your branch, so I'll continue this in https://github.com/innocenzi/laravel-vite/pull/259.

**Pull request closed without merging**
