### PR TITLE
fix: improve regex expression to allow default vite config.ts

### PR DESCRIPTION
**Pull request by melvin78**
Modify regex expression to allow for both 'vite.config.ts' and 'vite.dev.config.ts' to be found

### CODE REVIEW

**Comment by innocenzi** [comment]
Hey, I'm not sure I understand. `vite.config.ts` already works, as that's the default config Vite tries to read. Can you show me your `package.json` and `vite.config.ts` for me to understand the error you showed in https://github.com/innocenzi/laravel-vite/discussions/332?

**Comment by melvin78** [comment]
> Hey, I'm not sure I understand. `vite.config.ts` already works, as that's the default config Vite tries to read. Can you show me your `package.json` and `vite.config.ts` for me to understand the error you showed in #332?

sure . Here is the package.json

`{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@vitejs/plugin-vue": "^3.2.0",
        "@vue/compiler-sfc": "^3.2.45",
        "autoprefixer": "^10.4.13",
        "postcss": "^8.4.19",
        "tailwindcss": "^3.2.4",
        "vite": "^3.2.3",
        "vite-plugin-laravel": "^0.2.2"
    },
    "dependencies": {
        "vue": "^3.2.36",
        "@inertiajs/inertia": "^0.11.1",
        "@inertiajs/inertia-vue3": "^0.6.0"
    }
}`

and vite.config.ts

`import { defineConfig } from 'vite'
import tailwindcss from 'tailwindcss'
import autoprefixer from 'autoprefixer'
import laravel from 'vite-plugin-laravel'
import vue from '@vitejs/plugin-vue'
import inertia from './resources/scripts/vite/inertia-layout'

export default defineConfig({
	plugins: [
		inertia(),
		vue(),
		laravel({
			postcss: [
				tailwindcss(),
				autoprefixer(),
			],
		}),
	],
})
`

I didn't change anything this are the default configurations that come with when you use the preset and fresh installation of laravel. Tried running npm run dev but it would still not find the 'vite.config.ts'. Not until i changed it to vite.[something].ts

**Comment by innocenzi** [comment]
Sorry I forgot to ask you about your `config/vite.php` as well. The defaults should work, maybe there's something wrong with the preset - but what you changed affects reading the server-side config, not which `vite.config.ts` file is read

**Comment by innocenzi** [comment]
Closing for inactivity, feel free to reopen if still needed, with the missing details.

**Pull request closed without merging**
