### PR TITLE
feat: support remote manifests

### PR DESCRIPTION
**Pull request by WOSHIZHAZHA120**

### CODE REVIEW

**Comment by innocenzi** [comment]
Can you add tests?

**Comment by WOSHIZHAZHA120** [comment]
> Can you add tests?

finished, please review

**Review by innocenzi — APPROVED** [review]

**Comment by innocenzi** [comment]
Thanks! Please try not to update every changed file with your configured code style next time, though.

**Comment by WOSHIZHAZHA120** [comment]
Sorry, I'm not familiar with php-cs-fixer, can you tell me which command should I use?

**Comment by WOSHIZHAZHA120** [comment]
And did you forget to add a new config item in the config file?

**Comment by innocenzi** [comment]
> Sorry, I'm not familiar with php-cs-fixer, can you tell me which command should I use?

php-cs-fixer has no rules for this, but you changed whitespaces in a few places ([there](https://github.com/innocenzi/laravel-vite/pull/309/commits/909c50c7353bd8b89e398cb71a12423826048811#diff-b7c57c8fe4222bcf6ae806a98fb42f42434997ce6bdddbd37fcf1bf4fb005c2aR23-R24) and [there](https://github.com/innocenzi/laravel-vite/pull/309/commits/909c50c7353bd8b89e398cb71a12423826048811#diff-b7c57c8fe4222bcf6ae806a98fb42f42434997ce6bdddbd37fcf1bf4fb005c2aR361) for instance). No big deal but annoying for maintainers.

> And did you forget to add a new config item in the config file?

No, the third parameter is the value returned if it doesn't exist in the config. I think this feature is quite niche, and since it isn't documented I didn't feel like it needed to have a default value in the configuration file. Feel free to PR though!

**Comment by WOSHIZHAZHA120** [comment]
I think it would be better to change the config key?
after change the build_path, the build directory becomes /public/{url}, too long!

**Comment by innocenzi** [comment]
Feel free to PR whatever you need as long as it makes sense and you provide an explanation for the change 👍

**Pull request merged**
